- hosts: all
  connection: local
  tasks:
    - name: get current user
      shell: whoami
      register: current_user

- hosts: all
  connection: local
  become: true
  become_user: root
  roles:
    - common

- hosts: all
  connection: local
  roles:
    - git
