- name: install borgbackup dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - libssl-dev
    - openssl
    - libacl1-dev
    - libacl1
    - liblz4-dev
    - liblz4-1
    - build-essential
    - libfuse-dev
    - fuse
    - pkg-config

- name: install borgbackup
  pip:
    name: borgbackup[fuse]
    executable: pip3
