- name: add docker repo key
  apt_key:
    keyserver: eu.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  sudo: yes

- name: add docker repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    state: present
    update_cache: yes

- name: install docker
  apt:
    name: docker-engine

- name: add current user to docker group
  user:
    name: "{{ current_user.stdout }}"
    groups: docker
    append: yes
