- name: add hipchat repo key
  apt_key:
    url: https://www.hipchat.com/keys/hipchat-linux.key
    state: present
  sudo: yes

- name: add hipchat repo
  apt_repository:
    repo: 'deb http://hipchat.basecom.de/clients/linux/apt stable main'
    state: present
    update_cache: yes
  sudo: yes

- name: install hipchat
  apt:
    name: hipchat
    update_cache: yes
  sudo: yes
