- name: add hipchat repo key
  apt_key:
    url: https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public
    state: present

- name: add hipchat repo
  apt_repository:
    repo: 'deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client xenial main'
    state: present
    update_cache: yes

- name: install hipchat
  apt:
    name: hipchat4
