- name: install apt-transport-https
  apt:
    name: apt-transport-https

- name: add wire repo key
  apt_key:
    url: http://wire-app.wire.com/linux/releases.key
    state: present

- name: add wire repo
  apt_repository:
    repo: 'deb https://wire-app.wire.com/linux/debian stable main'
    state: present
    update_cache: yes

- name: install wire
  apt:
    name: wire-desktop
